USE [master]
GO
/****** Object:  Database [MyJWTDB]    Script Date: 2024-06-10 8:04:45 AM ******/
CREATE DATABASE [MyJWTDB] ON  PRIMARY 
( NAME = N'MyJWTDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MyJWTDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyJWTDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MyJWTDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyJWTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyJWTDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyJWTDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyJWTDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyJWTDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyJWTDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyJWTDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyJWTDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyJWTDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyJWTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyJWTDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyJWTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyJWTDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyJWTDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyJWTDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyJWTDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyJWTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyJWTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyJWTDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyJWTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyJWTDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyJWTDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyJWTDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyJWTDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MyJWTDB] SET  MULTI_USER 
GO
ALTER DATABASE [MyJWTDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyJWTDB] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MyJWTDB', N'ON'
GO
USE [MyJWTDB]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2024-06-10 8:04:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](300) NOT NULL,
	[HashPassword] [nvarchar](max) NOT NULL,
	[SaltPassword] [nvarchar](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[RoleId] [int] NULL,
	[RefreshToken] [nvarchar](max) NULL,
	[RefreshTokenExpiryTime] [datetime] NULL,
	[SessionId] [nvarchar](max) NULL,
	[TokenExpiryTime] [datetime] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([Id], [Username], [Email], [HashPassword], [SaltPassword], [IsActive], [RoleId], [RefreshToken], [RefreshTokenExpiryTime], [SessionId], [TokenExpiryTime]) VALUES (1, N'test', N'test@gmail.com', N'2n7AVMFhLjpVF5w1ZNvcYTKWuJFYjgErq6DVL9ft8ZLaNzG/HL6lHl1jhcNf4AqRtK4cjaJWXEbkGEcTV4suHg==', N'x03csuhGWiuO5SIrTEl83A==', 1, NULL, NULL, CAST(N'1994-06-10T08:02:37.287' AS DateTime), NULL, CAST(N'1994-06-10T08:02:37.287' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
USE [master]
GO
ALTER DATABASE [MyJWTDB] SET  READ_WRITE 
GO
